# Generated by Django 4.2.5 on 2023-11-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surtidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_combustible', models.CharField(max_length=10)),
                ('precio_por_litro', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('surtidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacion.surtidor')),
            ],
        ),
    ]
